#!/usr/bin/env python3
"""
Regenerate the Scanner launcher icon.

Four L-shaped corner brackets -- the same focus-bracket language LightOS's own camera
uses (`ic_camera_focus_locking` in `lightphone/light-sdk`) -- framing two short horizontal
bars standing in for lines of recognized text. White line art on black, matching every
sibling Light Phone III tool.

Geometry is defined once, in the 108x108 adaptive-icon canvas, and emitted twice -- as
Android vector paths and as raster fallbacks. Everything sits inside the 18..90 safe zone
so no launcher mask can clip it, and that is asserted rather than eyeballed.

    python3 scripts/generate_icon.py

Needs Pillow. Rewrites app/src/main/res/{drawable,mipmap-*}.
"""

from __future__ import annotations

import os

from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

CANVAS = 108
SAFE = (18, 90)

BRACKET_STROKE = 5.0
BRACKET_ARM = 16.0
FRAME = (22.0, 22.0, 86.0, 86.0)  # left, top, right, bottom

LINE_THICKNESS = 6.0
LINE_RADIUS = 3.0
LINE_Y = (46.0, 62.0)
LINE_X = (34.0, 74.0, 64.0)  # line 1 spans LINE_X[0]..LINE_X[1], line 2 spans LINE_X[0]..LINE_X[2]

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8


def check_safe_zone() -> None:
    lo, hi = SAFE
    edge = BRACKET_STROKE / 2
    left, top, right, bottom = FRAME
    extents = [
        (left - edge, top - edge),
        (right + edge, bottom + edge),
        (LINE_X[0], LINE_Y[0] - LINE_THICKNESS / 2),
        (LINE_X[1], LINE_Y[1] + LINE_THICKNESS / 2),
    ]
    for x, y in extents:
        assert lo <= x <= hi and lo <= y <= hi, f"({x}, {y}) escapes the safe zone"


def corner_paths() -> str:
    left, top, right, bottom = FRAME
    arm = BRACKET_ARM
    # Each corner is an "L": one arm along each edge, meeting at the corner.
    corners = [
        # top-left
        f"M {left},{top + arm} L {left},{top} L {left + arm},{top}",
        # top-right
        f"M {right - arm},{top} L {right},{top} L {right},{top + arm}",
        # bottom-right
        f"M {right},{bottom - arm} L {right},{bottom} L {right - arm},{bottom}",
        # bottom-left
        f"M {left + arm},{bottom} L {left},{bottom} L {left},{bottom - arm}",
    ]
    return " ".join(corners)


def line_path(x0: float, x1: float, y: float) -> str:
    r = LINE_RADIUS
    half = LINE_THICKNESS / 2
    top = y - half
    w = (x1 - x0) - 2 * r
    return (
        f"M {x0 + r},{top} h {w} a {r},{r} 0 0 1 {r},{r} "
        f"v {LINE_THICKNESS - 2 * r} a {r},{r} 0 0 1 {-r},{r} "
        f"h {-w} a {r},{r} 0 0 1 {-r},{-r} "
        f"v {-(LINE_THICKNESS - 2 * r)} a {r},{r} 0 0 1 {r},{-r} Z"
    )


def lines_path() -> str:
    return " ".join(
        [
            line_path(LINE_X[0], LINE_X[1], LINE_Y[0]),
            line_path(LINE_X[0], LINE_X[2], LINE_Y[1]),
        ]
    )


def write_vectors() -> None:
    background = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Pure black. On the Light Phone III's panel these pixels are simply off. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h{CANVAS}v{CANVAS}h-{CANVAS}z" />
</vector>
"""

    foreground = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by scripts/generate_icon.py -- edit the geometry there, not here.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{CANVAS}dp"
    android:height="{CANVAS}dp"
    android:viewportWidth="{CANVAS}"
    android:viewportHeight="{CANVAS}">
    <path
        android:pathData="{corner_paths()}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="{BRACKET_STROKE:g}"
        android:fillColor="#00000000"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />
    <path
        android:pathData="{lines_path()}"
        android:fillColor="#FFFFFF" />
</vector>
"""

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

    os.makedirs(os.path.join(RES, "drawable"), exist_ok=True)
    os.makedirs(os.path.join(RES, "mipmap-anydpi-v26"), exist_ok=True)
    with open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w") as f:
        f.write(background)
    with open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground)
    for name in ("ic_launcher", "ic_launcher_round"):
        with open(os.path.join(RES, "mipmap-anydpi-v26", f"{name}.xml"), "w") as f:
            f.write(adaptive)


def render(px: int, circular: bool) -> Image.Image:
    s = SUPERSAMPLE
    img = Image.new("RGBA", (CANVAS * s, CANVAS * s), (0, 0, 0, 255))
    d = ImageDraw.Draw(img)
    w = BRACKET_STROKE * s
    left, top, right, bottom = FRAME
    arm = BRACKET_ARM

    def seg(x0: float, y0: float, x1: float, y1: float) -> None:
        d.line([(x0 * s, y0 * s), (x1 * s, y1 * s)], fill=(255, 255, 255, 255), width=round(w))
        r = w / 2
        for (x, y) in ((x0, y0), (x1, y1)):
            d.ellipse(
                [x * s - r, y * s - r, x * s + r, y * s + r],
                fill=(255, 255, 255, 255),
            )

    # Four corner brackets, two arms each.
    seg(left, top + arm, left, top)
    seg(left, top, left + arm, top)
    seg(right - arm, top, right, top)
    seg(right, top, right, top + arm)
    seg(right, bottom - arm, right, bottom)
    seg(right, bottom, right - arm, bottom)
    seg(left + arm, bottom, left, bottom)
    seg(left, bottom, left, bottom - arm)

    for (x0, x1, y) in ((LINE_X[0], LINE_X[1], LINE_Y[0]), (LINE_X[0], LINE_X[2], LINE_Y[1])):
        half = LINE_THICKNESS / 2
        d.rounded_rectangle(
            [x0 * s, (y - half) * s, x1 * s, (y + half) * s],
            radius=LINE_RADIUS * s,
            fill=(255, 255, 255, 255),
        )

    lo, hi = SAFE
    out = img.crop((lo * s, lo * s, hi * s, hi * s)).resize((px, px), Image.LANCZOS)

    if circular:
        mask = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(mask).ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
        mask = mask.resize((px, px), Image.LANCZOS)
        base = Image.new("RGBA", (px, px), (0, 0, 0, 0))
        base.paste(out, (0, 0), mask)
        out = base
    return out


def write_rasters() -> None:
    for dpi, px in DENSITIES.items():
        folder = os.path.join(RES, f"mipmap-{dpi}")
        os.makedirs(folder, exist_ok=True)
        render(px, False).save(os.path.join(folder, "ic_launcher.png"))
        render(px, True).save(os.path.join(folder, "ic_launcher_round.png"))


if __name__ == "__main__":
    check_safe_zone()
    write_vectors()
    write_rasters()
    print("icon regenerated in", os.path.normpath(RES))
